---
bibliography: "input/bib/jusmer.bib"
csl: "input/bib/apa6.csl"
---

## Market justice preferences

In recent years, welfare states have undergone several institutional transformations, with market expansion strongly penetrating the field of social services in parallel to public provision [@busemeyer_welfare_2020]. Such processes have led to changes in the architecture of the institutions responsible for social welfare. On the one hand, private companies operate as service administrators of benefits based on the user's ability to pay, whereas on the other hand, public providers have reorganized to compete as quasi-markets [@lindh_it_2017]. Besides changes at the formal level, the commodification of social services shapes cultural norms and beliefs, an institutional impact referred to as *policy feedback effect*.[@beland_varieties_2019; @jaime-castillo_public_2013]. In this sense, markets operate as moral projects [@fourcade_moral_2007]. 

In the field of distributive justice, market preferences have gained relevance in attitudinal studies on redistribution. A seminal study in this area was performed by Kulegel [-@kluegel_beliefs_1981], analyzing the normative bases of beliefs about social stratification. In this context, market justice preferences emerge as a concept related to a normative principle that legitimizes access to goods and services based on an individual's or family's ability to pay [@lane_market_1986]. This market-oriented redistribution is closely related to the justification of inequalities, as it views the market as a space of equal opportunity, where economic success is understood as an individual outcome [@kluegel_legitimation_1999]. In this way, market justice legitimizes socioeconomic inequalities from an economic and moral perspective, ignoring the structural conditions that generate these disparities. 

Within the market justice framework, pensions are one of the central elements due to their centrality in discussions of economic distribution among the elderly population [@arenas_sistemas_2019]. Some pension systems are based on principles of solidarity, whereas others are based on privatization policies that manage resources according to a market logic [@arrizabalomontoro_debate_2019]. Such varying approaches certainly have cultural implications for societies. For example, market-oriented plans are associated with feelings of insecurity due to the individualization of risk. [@yen_pension_2018]. Therefore, distributive principles that shape pension systems could be mirrored in market justice preferences [@castillo_perceptions_2025].

Recent literature on market preferences has found relevant associations with both individual and contextual factors. Various studies suggest that individuals with higher socioeconomic status tend to exhibit greater market preferences than those in more disadvantaged social positions [@koos_moral_2019; @lindh_public_2015]. Similarly, political ideology has been linked to preferences for market justice, with right-wing individuals mostly supporting market-oriented distribution [@castillo_socialization_2024; @lee_fairness_2024]. These trends reflect a moral economy based on the justification of status by those who benefit from the market. Regarding contextual factors, the evidence suggests that in countries with greater private investment in services, individuals tend to decrease their preferences for redistribution, internalizing the market order as a criterion of justice, whereas the opposite occurs in countries where public provision of services prevails [@busemeyer_education_2013; @lindh_public_2015; @immergut_it_2020]. 

Most of the research in this area have relied on survey data. In such studies, questions about market justice ask directly about the support for the provision of social services (as education, pensions, and health) based on individual payment capacity (i.e: “Is it fair that high-income individuals have better pensions than lower-income individuals?”) [@lindh_public_2015; @kerner_pension_2020; @busemeyer_education_2013].  The International Social Survey Programme (ISSP) has been a key resource for developing a market justice agenda. Based on the ISSP measurement proposal, some researches have measured market preferences using an index constructed from the corresponding items [@castillo_perceptions_2025], whereas others analyze the items separately. Nevertheless, market justice preferences in pensions are a sidelined area in this agenda, as ISSP does not include an item referring to pensions (only health and education). 
