# Helper function to render the allocation slider widget.
# id: the surveydown question id (e.g. "cbc_q1", "cbc_practice")
# nombre1, nombre2: optional names to display instead of "Opción 1" and "Opción 2"
allocation_slider <- function(id, total_budget = 1500000, nombre1 = "Opción 1", nombre2 = "Opción 2") {
  htmltools::browsable(htmltools::tagList(
    # Slider
    shiny::div(
      style = "margin: -30px 0 16px 0;",
      sd_question(
        type    = "slider_numeric",
        id      = id,
        label   = "",
        option  = 0:100,
        grid    = FALSE,
        default = 50,
        width   = "100%"
      )
    ),

    # Allocation display boxes
    shiny::div(
      style = "display: flex; gap: 8px; justify-content: center; margin-top: 14px;",
      shiny::div(
        style = "border: 2px solid #28a745; padding: 8px 4px; border-radius: 5px; text-align: center; flex: 1; min-width: 0; background-color: #f0fff4; position: relative; overflow: hidden;",
        shiny::div(id = paste0(id, "_shade1"), style = "position: absolute; left: 0; right: 0; bottom: 0; height: 50%; background: rgba(40, 167, 69, 0.18); pointer-events: none; transition: height 120ms linear; z-index: 0;"),
        shiny::div(
          style = "position: relative; z-index: 1;",
          shiny::h4(shiny::span(id = paste0(id, "_name1"), nombre1, style = "color: #28a745; font-weight: 800;"), style = "margin: 0 0 4px 0; font-size: 0.9rem;"),
          shiny::h3(shiny::span(id = paste0(id, "_opt1"), "$750.000", style = ""), style = "color: #28a745; margin: 4px 0; font-weight: 900; font-size: 1.1rem;"),
          shiny::p(shiny::span(id = paste0(id, "_opt1_pct"), "50%", style = ""), style = "color: #28a745; font-size: 14px; margin: 2px 0; font-weight: 800;")
        )
      ),
      shiny::div(
        style = "border: 2px solid #007bff; padding: 8px 4px; border-radius: 5px; text-align: center; flex: 1; min-width: 0; background-color: #f0f8ff; position: relative; overflow: hidden;",
        shiny::div(id = paste0(id, "_shade2"), style = "position: absolute; left: 0; right: 0; bottom: 0; height: 50%; background: rgba(0, 123, 255, 0.18); pointer-events: none; transition: height 120ms linear; z-index: 0;"),
        shiny::div(
          style = "position: relative; z-index: 1;",
          shiny::h4(shiny::span(id = paste0(id, "_name2"), nombre2, style = "color: #007bff; font-weight: 800;"), style = "margin: 0 0 4px 0; font-size: 0.9rem;"),
          shiny::h3(shiny::span(id = paste0(id, "_opt2"), "$750.000", style = ""), style = "color: #007bff; margin: 4px 0; font-weight: 900; font-size: 1.1rem;"),
          shiny::p(shiny::span(id = paste0(id, "_opt2_pct"), "50%", style = ""), style = "color: #007bff; font-size: 14px; margin: 2px 0; font-weight: 800;")
        )
      )
    ),

    # Slider CSS
    shiny::tags$style(HTML(paste0(
      "#container-", id, " { margin-bottom: 2px !important; }",
      "#container-", id, " .form-group { margin-bottom: 2px !important; }",
      "#container-", id, " .irs { margin-top: 0 !important; margin-bottom: 10px !important; height: 26px !important; }",
      "#container-", id, " .irs-grid, #container-", id, " .irs-grid-text, #container-", id, " .irs-min, #container-", id, " .irs-max, #container-", id, " .irs-single { display: none !important; }",
      "#", id, " .irs-bar { background: #28a745 !important; height: 10px !important; }",
      "#", id, " .irs-bar-edge { background: #28a745 !important; }",
      "#", id, " .irs-line { background: #007bff !important; background-color: #007bff !important; background-image: none !important; border-color: #007bff !important; }",
      "#", id, "_name1 { color: #28a745 !important; font-weight: 800 !important; }",
      "#", id, "_name2 { color: #007bff !important; font-weight: 800 !important; }",
      "table.table-striped.table-hover.table-condensed > tbody > tr:first-child > td:nth-child(2) { color: #28a745 !important; font-weight: 800 !important; }",
      "table.table-striped.table-hover.table-condensed > tbody > tr:first-child > td:nth-child(3) { color: #007bff !important; font-weight: 800 !important; }",
      "@media (max-width: 576px) {",
      "#container-", id, " { margin-bottom: 0 !important; }",
      "#container-", id, " .irs { margin-top: 0 !important; margin-bottom: 8px !important; height: 22px !important; }",
      "#", id, "_opt1, #", id, "_opt2 { font-size: 1.1rem !important; }",
      "#", id, "_opt1_pct, #", id, "_opt2_pct { font-size: 0.95rem !important; }",
      "}"
    ))),

    # JavaScript to update allocation display
    shiny::tags$script(htmltools::HTML(paste0(
      "(function() {",
      "  const sliderId = '", id, "';",
      "  const totalBudget = ", total_budget, ";",
      "  ",
      "  function parsePct(x) {",
      "    const n = parseInt(String(x).replace('%', '').trim(), 10);",
      "    return Number.isFinite(n) ? Math.max(0, Math.min(100, n)) : null;",
      "  }",
      "  ",
      "  function getSliderValue() {",
      "    const sliderEl = document.getElementById(sliderId);",
      "    if (!sliderEl) return 50;",
      "    const fromValue = parsePct(sliderEl.value);",
      "    if (fromValue !== null) return fromValue;",
      "    const dataFrom = parsePct(sliderEl.getAttribute('data-from'));",
      "    if (dataFrom !== null) return dataFrom;",
      "    const irsFrom = sliderEl.parentElement ? sliderEl.parentElement.querySelector('.irs-from') : null;",
      "    const fromText = parsePct(irsFrom ? irsFrom.textContent : null);",
      "    if (fromText !== null) return fromText;",
      "    return 50;",
      "  }",
      "  ",
      "  function updateAllocation() {",
      "    const pct1 = getSliderValue();",
      "    const pct2 = 100 - pct1;",
      "    const opt1 = totalBudget * (pct1 / 100);",
      "    const opt2 = totalBudget * (pct2 / 100);",
      "    const fmt = (x) => '$' + Math.round(x).toLocaleString('es-ES');",
      "    const opt1El = document.getElementById('", id, "_opt1');",
      "    const opt2El = document.getElementById('", id, "_opt2');",
      "    const pct1El = document.getElementById('", id, "_opt1_pct');",
      "    const pct2El = document.getElementById('", id, "_opt2_pct');",
      "    const shade1El = document.getElementById('", id, "_shade1');",
      "    const shade2El = document.getElementById('", id, "_shade2');",
      "    if (opt1El) opt1El.textContent = fmt(opt1);",
      "    if (opt2El) opt2El.textContent = fmt(opt2);",
      "    if (pct1El) pct1El.textContent = pct1 + '%';",
      "    if (pct2El) pct2El.textContent = pct2 + '%';",
      "    if (shade1El) shade1El.style.height = pct1 + '%';",
      "    if (shade2El) shade2El.style.height = pct2 + '%';",
      "  }",
      "  ",
      "  function findTableNames() {",
      "    let allTables = document.querySelectorAll('table.table-striped.table-hover.table-condensed');",
      "    if (allTables.length === 0) return null;",
      "    const sliderEl = document.getElementById(sliderId);",
      "    if (!sliderEl) return null;",
      "    const sliderPos = sliderEl.getBoundingClientRect().top;",
      "    let closestTable = null;",
      "    let closestDist = Infinity;",
      "    allTables.forEach(function(table) {",
      "      const tablePos = table.getBoundingClientRect().top;",
      "      if (tablePos < sliderPos) {",
      "        const dist = sliderPos - tablePos;",
      "        if (dist < closestDist) {",
      "          closestDist = dist;",
      "          closestTable = table;",
      "        }",
      "      }",
      "    });",
      "    if (closestTable) {",
      "      const rows = closestTable.querySelectorAll('tbody tr');",
      "      for (let i = 0; i < rows.length; i++) {",
      "        const cells = rows[i].querySelectorAll('td');",
      "        if (cells.length >= 3 && cells[0].textContent.trim() === 'Postulante:') {",
      "          const name1 = cells[1].textContent.trim();",
      "          const name2 = cells[2].textContent.trim();",
      "          if (name1 && name2) return [name1, name2];",
      "        }",
      "      }",
      "    }",
      "    return null;",
      "  }",
      "  ",
      "  function updateNames() {",
      "    const publishedNames = window.cbc_names && window.cbc_names[sliderId];",
      "    const names = (Array.isArray(publishedNames) && publishedNames.length === 2) ? publishedNames : findTableNames();",
      "    const name1El = document.getElementById('", id, "_name1');",
      "    const name2El = document.getElementById('", id, "_name2');",
      "    if (name1El) {",
      "      name1El.style.color = '#28a745';",
      "      name1El.style.fontWeight = '800';",
      "    }",
      "    if (name2El) {",
      "      name2El.style.color = '#007bff';",
      "      name2El.style.fontWeight = '800';",
      "    }",
      "    if (names && names.length === 2) {",
      "      if (name1El) name1El.textContent = names[0];",
      "      if (name2El) name2El.textContent = names[1];",
      "    }",
      "    // Also color the Postulante row in the table itself",
      "    const allTables2 = document.querySelectorAll('table.table-condensed');",
      "    const sliderEl2 = document.getElementById(sliderId);",
      "    if (sliderEl2) {",
      "      const sliderPos2 = sliderEl2.getBoundingClientRect().top;",
      "      let closest2 = null, closestDist2 = Infinity;",
      "      allTables2.forEach(function(t) {",
      "        const tp = t.getBoundingClientRect().top;",
      "        if (tp < sliderPos2 && sliderPos2 - tp < closestDist2) {",
      "          closestDist2 = sliderPos2 - tp; closest2 = t;",
      "        }",
      "      });",
      "      if (closest2) {",
      "        const rows2 = closest2.querySelectorAll('tbody tr');",
      "        for (let i = 0; i < rows2.length; i++) {",
      "          const cells2 = rows2[i].querySelectorAll('td');",
      "          if (cells2.length >= 3 && cells2[0].textContent.trim() === 'Postulante:') {",
      "            cells2[1].style.setProperty('color', '#28a745', 'important');",
      "            cells2[1].style.setProperty('font-weight', '800', 'important');",
      "            cells2[2].style.setProperty('color', '#007bff', 'important');",
      "            cells2[2].style.setProperty('font-weight', '800', 'important');",
      "            break;",
      "          }",
      "        }",
      "      }",
      "    }",
      "  }",
      "  ",
      "  function init() {",
      "    updateAllocation();",
      "    updateNames();",
      "  }",
      "  ",
      "  init();",
      "  setTimeout(init, 50);",
      "  setTimeout(init, 300);",
      "  setTimeout(init, 900);",
      "  if (document.readyState === 'loading') {",
      "    document.addEventListener('DOMContentLoaded', init);",
      "  }",
      "  window.addEventListener('load', init);",
      "  ",
      "  setInterval(init, 500);",
      "  ",
      "  function bindListeners() {",
      "    const sliderEl = document.getElementById(sliderId);",
      "    if (sliderEl && !sliderEl.dataset.allocBound) {",
      "      sliderEl.addEventListener('change', updateAllocation);",
      "      sliderEl.addEventListener('input', updateAllocation);",
      "      sliderEl.dataset.allocBound = '1';",
      "    }",
      "  }",
      "  bindListeners();",
      "  setInterval(bindListeners, 1000);",
      "})();",
      ""
    )))
  ))
}

