# ! JUST READ - don't change the content of this file
# All survey configuration settings with final resolved values

theme-settings:
  theme: flatly
  barposition: top
  barcolor: '#841414'
  footer-left: ''
  footer-center: ''
  footer-right: ''

survey-settings:
  show-previous: yes
  use-cookies: yes
  auto-scroll: yes
  rate-survey: no
  all-questions-required: no
  start-page: ~
  system-language: es
  highlight-unanswered: yes
  highlight-color: orange
  capture-metadata: yes
  required-questions:
  - consent_understand
  - respondent
  - sexo
  - year_of_birth
  - education
  - manip_check
  - cbc_practice
  - cbc_q1
  - cbc_q2
  - cbc_q3
  - cbc_q4
  - cbc_q5
  - cbc_q6
  - mj_1
  - mj_2
  - mj_3
  - ref_1
  - ref_2
  - ref_3
  - proy_1
  - proy_2
  - rank_1
  - rank_2
  - rank_3
  - rank_4
  - rank_5
  - pres_1
  - pres_2
  - pres_3
  - pres_4
  - pres_5
  - pres_6
  - valor_1
  - valor_2
  - valor_3
  - valor_4
  - valor_5
  - dec_3
  - dec_1
  - dec_2
  - lucro_1
  - lucro_2
  - lucro_3
  - cargo_1
  - cargo_2
  - cargo_3
  - cargo_4
  - cargo_5
  - efic_1
  - efic_2
  - efic_3
  - efic_4
  - efic_5
  - part_1
  - part_2
  - part_3
  - part_4
  - part_5
  - neolib_1
  - neolib_2
  - neolib_3
  - neolib_4
  - control_1
  - control_2
  - control_3
  - actitud_1
  - actitud_2
  - reciproc_1
  - reciproc_2
  - reciproc_3
  - actitud_4
  - id_1
  - id_2
  - id_3
  - nec_1
  - nec_2
  - nec_3
  - esf_1
  - esf_2
  - esf_3
  - esf_4
  - esf_5
  - adc_qstn
  - adc_5
  - adc_6
  - adc_7
  - gender
  - income
  - salud_prov
  - educ_prov

system-messages:
  cancel: Cancelar
  confirm-exit: Confirmar Salida
  sure-exit: ¿Está seguro de que desea salir de la encuesta?
  submit-exit: Enviar y Salir
  warning: Advertencia
  required: Por favor, responda todas las preguntas obligatorias antes de continuar.
  rating-title: Antes de irse...
  rating-text: 'Califique su experiencia en la encuesta:'
  rating-scale: de 1-malo a 5-excelente
  previous: Anterior
  next: Página siguiente
  exit: Finalizar encuesta
  close-tab: Por favor, cierre esta pestaña manualmente para salir de la encuesta.
  choose-option: Elija una opción...
  click: Haga clic aquí
  redirect: Redireccionando en
  seconds: segundos
  new-tab: Se abre en una nueva pestaña
  redirect-error: 'Error: Este texto no activará ninguna redirección...'
