# ! JUST READ - don't change the content of this file
# All survey configuration settings with final resolved values

theme-settings:
  theme: flatly
  barposition: top
  barcolor: '#841414'
  footer-left: Hecho con [surveydown](https://surveydown.org)
  footer-center: JUSMER – Proyecto FONDECYT
  footer-right: '[<i class="bi bi-github"></i> Repositorio GitHub](https://github.com/surveydown-dev/template_default)'

survey-settings:
  show-previous: yes
  use-cookies: yes
  auto-scroll: yes
  rate-survey: no
  all-questions-required: no
  start-page: welcome
  system-language: es
  highlight-unanswered: yes
  highlight-color: orange
  capture-metadata: yes
  required-questions: consent_understand

system-messages:
  cancel: Cancelar
  confirm-exit: Confirmar Salida
  sure-exit: ¿Está seguro de que desea salir de la encuesta?
  submit-exit: Enviar y Salir
  warning: Advertencia
  required: Por favor, responda todas las preguntas obligatorias antes de continuar.
  rating-title: Antes de irse...
  rating-text: 'Califique su experiencia en la encuesta:'
  rating-scale: de 1-malo a 5-excelente
  previous: Página anterior
  next: Página siguiente
  exit: Finalizar encuesta
  close-tab: Por favor, cierre esta pestaña manualmente para salir de la encuesta.
  choose-option: Elija una opción...
  click: Haga clic aquí
  redirect: Redireccionando en
  seconds: segundos
  new-tab: Se abre en una nueva pestaña
  redirect-error: 'Error: Este texto no activará ninguna redirección...'
